### ISSUE TITLE
StandardActions config parsing broken when missing

### ISSUE THREAD

**Issue by josler** [Betterment/betterlint#7]
Here I upgraded from 1.0 to 1.1 and things broke with this error - we probably want to use fetch and default that one :)

```
An error occurred while Betterment/NonStandardActions cop was inspecting /Users/jamie/src/equals/test/controllers/application_controller_test.rb:123:4.
undefined method `+' for nil:NilClass

          @allowed_actions ||= cop_config['StandardActions'] + cop_config['AdditionalAllowedActions'] # rubocop:disable InternalAffairs/UndefinedConfig
                                                             ^
/Users/jamie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/betterlint-1.1.0/lib/rubocop/cop/betterment/non_standard_actions.rb:65:in `allowed_actions'
/Users/jamie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/betterlint-1.1.0/lib/rubocop/cop/betterment/non_standard_actions.rb:69:in `allowed_action?'
/Users/jamie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/betterlint-1.1.0/lib/rubocop/cop/betterment/non_standard_actions.rb:58:in `check_raw_route'
/Users/jamie/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/betterlint-1.1.0/lib/rubocop/cop/betterment/non_standard_actions.rb:34:in `block in on_block'
```

**Comment by smudge** [comment]
Hi @josler -- I'm trying to reproduce this issue! That should have default values provided by [the YML config](https://github.com/Betterment/betterlint/blob/97d723a95b586736b27a3dfd4deff8809580ace6/config/default.yml#L59), so I'm wondering if maybe you're doing something other than using `inherit_gem` to load that default config:

```yml
inherit_gem:
  betterlint:
    - config/default.yml
```
